version: '3.7'
services:
  api:
    build:
      context: .
    ports:
      - 3030:3030
    env_file: .env
    volumes:
      - ./main.py:/app/main.py
      - ./api:/app/api
      - ./tests:/app/tests
    command:
      [
        "uvicorn",
        "main:api",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload"
      ]