version: '3.9'
services:
  api:
    build:
      context: ./nomad-server
      dockerfile: Dockerfile
    volumes:
      - ./nomad-server/api:/src
    restart: "always"
    expose:
      - 8080
    command:
      [
        "uvicorn",
        "main:api",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload"
      ]
  
  ui:
    build: 
      context: ./nomad-ui
      dockerfile: Dockerfile
    volumes:
    - ./nomad-ui/public:/app/public
    - ./nomad-ui/src:/app/src
    - ./nomad-ui/index.html:/app/index.html
    - ./nomad-ui/tsconfig.json:/app/tsconfig.json
    - ./nomad-ui/tsconfig.vue-tsc.json:/app/tsconfig.vue-tsc.json
    - ./nomad-ui/quasar.config.js:/app/quasar.config.js
    - ./nomad-ui/postcss.config.cjs:/app/postcss.config.cjs
    - ./nomad-ui/package.json:/app/package.json
    - ./nomad-ui/package-lock.json:/app/package-lock.json
    command: quasar dev
